CREATE TABLE tx_seoassistant_gsc_row (
    uid int(11) unsigned NOT NULL auto_increment,
    pid int(11) DEFAULT '0' NOT NULL,
    tstamp int(11) unsigned DEFAULT '0' NOT NULL,
    crdate int(11) unsigned DEFAULT '0' NOT NULL,
    site_url varchar(512) DEFAULT '' NOT NULL,
    page_url varchar(2048) DEFAULT '' NOT NULL,
    query_text varchar(1024) DEFAULT '' NOT NULL,
    country varchar(16) DEFAULT '' NOT NULL,
    device varchar(32) DEFAULT '' NOT NULL,
    search_type varchar(32) DEFAULT 'web' NOT NULL,
    date_from int(11) unsigned DEFAULT '0' NOT NULL,
    date_to int(11) unsigned DEFAULT '0' NOT NULL,
    clicks double DEFAULT '0' NOT NULL,
    impressions double DEFAULT '0' NOT NULL,
    ctr double DEFAULT '0' NOT NULL,
    position double DEFAULT '0' NOT NULL,
    row_hash varchar(64) DEFAULT '' NOT NULL,
    raw_json mediumtext,

    PRIMARY KEY (uid),
    UNIQUE KEY row_hash (row_hash),
    KEY page_url (page_url(191)),
    KEY query_text (query_text(191)),
    KEY date_range (date_from,date_to)
);

CREATE TABLE tx_seoassistant_gsc_insight (
    uid int(11) unsigned NOT NULL auto_increment,
    pid int(11) DEFAULT '0' NOT NULL,
    tstamp int(11) unsigned DEFAULT '0' NOT NULL,
    crdate int(11) unsigned DEFAULT '0' NOT NULL,
    page_uid int(11) unsigned DEFAULT '0' NOT NULL,
    page_url varchar(2048) DEFAULT '' NOT NULL,
    query_text varchar(1024) DEFAULT '' NOT NULL,
    current_from int(11) unsigned DEFAULT '0' NOT NULL,
    current_to int(11) unsigned DEFAULT '0' NOT NULL,
    previous_from int(11) unsigned DEFAULT '0' NOT NULL,
    previous_to int(11) unsigned DEFAULT '0' NOT NULL,
    current_clicks double DEFAULT '0' NOT NULL,
    current_impressions double DEFAULT '0' NOT NULL,
    current_ctr double DEFAULT '0' NOT NULL,
    current_position double DEFAULT '0' NOT NULL,
    previous_clicks double DEFAULT '0' NOT NULL,
    previous_impressions double DEFAULT '0' NOT NULL,
    previous_ctr double DEFAULT '0' NOT NULL,
    previous_position double DEFAULT '0' NOT NULL,
    clicks_delta double DEFAULT '0' NOT NULL,
    impressions_delta double DEFAULT '0' NOT NULL,
    ctr_delta double DEFAULT '0' NOT NULL,
    position_delta double DEFAULT '0' NOT NULL,
    trend_type varchar(64) DEFAULT '' NOT NULL,
    priority int(11) unsigned DEFAULT '0' NOT NULL,
    summary text,
    evidence_json mediumtext,
    insight_hash varchar(64) DEFAULT '' NOT NULL,

    PRIMARY KEY (uid),
    UNIQUE KEY insight_hash (insight_hash),
    KEY page_uid (page_uid),
    KEY page_url (page_url(191)),
    KEY query_text (query_text(191)),
    KEY current_range (current_from,current_to),
    KEY trend_priority (trend_type,priority)
);

CREATE TABLE tx_seoassistant_page_snapshot (
    uid int(11) unsigned NOT NULL auto_increment,
    pid int(11) DEFAULT '0' NOT NULL,
    tstamp int(11) unsigned DEFAULT '0' NOT NULL,
    crdate int(11) unsigned DEFAULT '0' NOT NULL,
    page_uid int(11) unsigned DEFAULT '0' NOT NULL,
    page_url varchar(2048) DEFAULT '' NOT NULL,
    title varchar(512) DEFAULT '' NOT NULL,
    seo_title varchar(512) DEFAULT '' NOT NULL,
    description text,
    slug varchar(2048) DEFAULT '' NOT NULL,
    h1 varchar(512) DEFAULT '' NOT NULL,
    content_text mediumtext,
    word_count int(11) unsigned DEFAULT '0' NOT NULL,
    robots varchar(128) DEFAULT '' NOT NULL,
    canonical_url varchar(2048) DEFAULT '' NOT NULL,
    raw_json mediumtext,

    PRIMARY KEY (uid),
    UNIQUE KEY page_uid (page_uid),
    KEY page_url (page_url(191))
);

CREATE TABLE tx_seoassistant_rendered_snapshot (
    uid int(11) unsigned NOT NULL auto_increment,
    pid int(11) DEFAULT '0' NOT NULL,
    tstamp int(11) unsigned DEFAULT '0' NOT NULL,
    crdate int(11) unsigned DEFAULT '0' NOT NULL,
    url varchar(2048) DEFAULT '' NOT NULL,
    url_hash varchar(64) DEFAULT '' NOT NULL,
    http_status int(11) unsigned DEFAULT '0' NOT NULL,
    final_url varchar(2048) DEFAULT '' NOT NULL,
    html_title varchar(512) DEFAULT '' NOT NULL,
    meta_description text,
    canonical_url varchar(2048) DEFAULT '' NOT NULL,
    robots varchar(128) DEFAULT '' NOT NULL,
    headings_json mediumtext,
    links_json mediumtext,
    images_json mediumtext,
    structured_data_json mediumtext,
    visible_text mediumtext,
    word_count int(11) unsigned DEFAULT '0' NOT NULL,
    h1_count int(11) unsigned DEFAULT '0' NOT NULL,
    image_count int(11) unsigned DEFAULT '0' NOT NULL,
    missing_alt_count int(11) unsigned DEFAULT '0' NOT NULL,
    internal_link_count int(11) unsigned DEFAULT '0' NOT NULL,
    external_link_count int(11) unsigned DEFAULT '0' NOT NULL,
    issues_json mediumtext,

    PRIMARY KEY (uid),
    UNIQUE KEY url_hash (url_hash),
    KEY url (url(191)),
    KEY http_status (http_status),
    KEY missing_alt_count (missing_alt_count),
    KEY word_count (word_count)
);

CREATE TABLE tx_seoassistant_recommendation (
    uid int(11) unsigned NOT NULL auto_increment,
    pid int(11) DEFAULT '0' NOT NULL,
    tstamp int(11) unsigned DEFAULT '0' NOT NULL,
    crdate int(11) unsigned DEFAULT '0' NOT NULL,
    page_uid int(11) unsigned DEFAULT '0' NOT NULL,
    page_url varchar(2048) DEFAULT '' NOT NULL,
    query_text varchar(1024) DEFAULT '' NOT NULL,
    recommendation_type varchar(64) DEFAULT '' NOT NULL,
    priority int(11) unsigned DEFAULT '0' NOT NULL,
    status varchar(32) DEFAULT 'draft' NOT NULL,
    issue text,
    recommendation mediumtext,
    action_type varchar(64) DEFAULT '' NOT NULL,
    action_payload_json mediumtext,
    apply_capability varchar(32) DEFAULT 'manual' NOT NULL,
    proposed_seo_title varchar(512) DEFAULT '' NOT NULL,
    proposed_description text,
    evidence_json mediumtext,
    ai_model varchar(128) DEFAULT '' NOT NULL,
    dedupe_hash varchar(64) DEFAULT '' NOT NULL,
    applied_changes_json mediumtext,
    verification_status varchar(32) DEFAULT 'not_checked' NOT NULL,
    verification_json mediumtext,
    approved_at int(11) unsigned DEFAULT '0' NOT NULL,
    applied_at int(11) unsigned DEFAULT '0' NOT NULL,
    verified_at int(11) unsigned DEFAULT '0' NOT NULL,

    PRIMARY KEY (uid),
    UNIQUE KEY dedupe_hash (dedupe_hash),
    KEY page_uid (page_uid),
    KEY page_url (page_url(191)),
    KEY query_text (query_text(191)),
    KEY status_priority (status,priority),
    KEY apply_capability (apply_capability),
    KEY verification_status (verification_status)
);

CREATE TABLE tx_seoassistant_ai_run (
    uid int(11) unsigned NOT NULL auto_increment,
    pid int(11) DEFAULT '0' NOT NULL,
    tstamp int(11) unsigned DEFAULT '0' NOT NULL,
    crdate int(11) unsigned DEFAULT '0' NOT NULL,
    model varchar(128) DEFAULT '' NOT NULL,
    mode varchar(32) DEFAULT 'ai' NOT NULL,
    pages_analyzed int(11) unsigned DEFAULT '0' NOT NULL,
    recommendations_generated int(11) unsigned DEFAULT '0' NOT NULL,
    recommendations_stored int(11) unsigned DEFAULT '0' NOT NULL,
    focus_summary text,
    context_json mediumtext,

    PRIMARY KEY (uid),
    KEY crdate (crdate),
    KEY mode (mode)
);
